name: Check Master Merged

on:
  pull_request:
    branches:
      - master

jobs:
  check-master-merged:
    runs-on: ubuntu-latest
    if: github.head_ref == 'merge-upstream'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin master

      - name: Check if master is merged
        run: |
          git checkout merge-upstream
          if git merge-base --is-ancestor origin/master HEAD; then
            exit 0
          else
            echo "Master branch is NOT merged into this branch."
            exit 1
          fi
