name: Merge Upstream

on:
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: 'm-dzianishchyts/Paradise-SS220'
      TARGET_BRANCH: 'master'

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub googletrans==4.0.0-rc1

      - name: Download the script
        run: |
          wget https://raw.githubusercontent.com/${{ env.TARGET_REPO }}/${{ env.TARGET_BRANCH }}/tools/changelog/changelog_utils.py
          wget https://raw.githubusercontent.com/${{ env.TARGET_REPO }}/${{ env.TARGET_BRANCH }}/tools/merge-upstream/merge_upstream.py

      - name: Run the script
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          UPSTREAM_REPO: 'ParadiseSS13/Paradise'
          UPSTREAM_BRANCH: 'master'
          MERGE_BRANCH: 'merge-upstream-test'
          TRANSLATE_CHANGES: 'true'
          CHANGELOG_AUTHOR: 'ParadiseSS13'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Upstream Sync"
          python3 merge_upstream.py
